#!/bin/bash
#
# This script is a wrapper around (and in its full version an extension of) ximera's xake command
#  THAT ENSURES IT'S RUNNING IN A DOCKER CONTAINER 
#
# Usage: 
#   xmlatex bake
#   xmlatex bake test/myximerafile.tex
#   xmlatex bash   # gets a bash-shell INSIDE the container
#   xmlatex frost
#   xmlatex serve
#   xmlatex name
#   xmlatex all    # runs bake / frost / serve
#
# Advanced usage
#   XAKE_IMAGE=ghcr.io/ximeraproject/xake2023:latest xmlatex compile demo.tex    # use a different docker image
#   COMMAND=pdflatex xmlatex demo.tex                                            # do not run the xake-wrapper, but $COMMAND
#
# This script
#  - loads some configuration from ./xmScripts/config.tex (can be overwritten with CONFIG_FILE)
#  - for serving, also (basefolder)/$XM_KEYFILE (default .xmKeyFile) will be read (for GPG key settings)
#  - starts a xake docker container (unless we're already IN a container)
#  - starts (presumably) a container-specific version of this very script
#  - that (presumably) starts (lua-)xake with the arguments passed to this script
#  - optionally gets you a shell inside the container
#  - optionally automates lots of other things
#
# Note: set environment variable 'export DEBUG=1' and/or use -d option for debugging/tracing
# Note: this scrips RESTARTS itself (or a variant of itself!!!) IN A DOCKER CONTAINER
#
#

: "${CONFIG_FILE:=./xmScripts/config.txt}"

if [[ -f "$CONFIG_FILE" ]]
then
        [[ -n "$DEBUG" ]] && echo "Loading settings from config file $CONFIG_FILE."
        . $CONFIG_FILE
fi


# Set some defaults
#
# default docker image to run; overwrite with 'export XAKE_IMAGE=myxake:0.1'
: "${XAKE_BASE:=ximeralatex}"
: "${XAKE_VERSION:=v2.5.10}"
# : "${XAKE_BASE:=xake2019}"
# : "${XAKE_VERSION:=v2.1.1}"
: "${XAKE_CONTAINER:=$XAKE_BASE:$XAKE_VERSION}"
: "${DOCKER_REPO:=ghcr.io/ximeraproject/}"

# For historic compatibility, keep supporting XAKE_IMAGE
: "${XAKE_IMAGE:=$DOCKER_REPO$XAKE_CONTAINER}"   # TO BE OBSOLETED
: "${DOCKER_IMAGE:=$XAKE_IMAGE}"

: "${SERVER_PORT:=2000}"
: "${SERVER_NAME:=ximeraserver}"
: "${SERVER_IMAGE:=registry.gitlab.kuleuven.be/wet/ximera/ximeradocker:2.3_b}"

# How to sync DevEnvFiles (.vscode/.devcontainer/xmScripts)
: "${DEVENV_TGZFILE:=xmDevEnvFiles.tgz}"
: "${DEVENV_VERSION:=releases/latest/download}"
# : "${DEVENV_VERSION:=releases/download/v2.4.2}"   # Note the inversed order !!!!
: "${DEVENV_REPO:=ximeraProject/ximeraNewProject}"
: "${DEVENV_URL:=https://github.com/$DEVENV_REPO/$DEVENV_VERSION/xmDevEnvFiles.tgz}"


#
# Which folder to mount INSIDE the container, under /code  (use with care: it should contain a build.sh !)
: "${MOUNTDIR:=$(pwd)}"
: "${XM_KEYFILE:=.xmKeyFile}"
#
# Which script to start inside the container; 
: "${COMMAND:=xmlatex}"
# : "${COMMAND:=pdflatex}"     # skip xmlatex inside the container, and directly run a specific command ...    


if [[ -f /.dockerenv ]]  
then
    [[ -n "$DEBUG" ]] && echo "Running in docker container (with local hostname $HOSTNAME)"
elif [[ -n "$KUBERNETES_SERVICE_HOST" ]] 
then
    echo "Running in kubernetes container ($KUBERNETES_SERVICE_HOST)"
else 
    [[ -n "$DEBUG" ]] && echo "Running $0 on host ($HOSTNAME)"

    if [[ "$1" == "-i" ]]
    then
        INTERACTIVE="-it"  # start an interactive docker session (i.e. with a terminal attached)
        shift 
    fi 

    # make the -i default for bash (finally ...)
    if [[ "$1" == "bash" ]]
    then
        INTERACTIVE="-it"  # start an interactive docker session (i.e. with a terminal attached)
    fi 

    # LOCAL_IP is only needed if you want to serve to a ximeraServer on your localhost; do NOT use XIMERA_URL when using LOCAL_IP
    # TODO: is it still needed at all ????   The hostname -I confuses MacOS !
    if [[ "$LOCAL_IP" == "" ]]
    then
        LOCAL_IP=$(set -- $(hostname -I); echo "$1")
        [[ -n "$DEBUG" ]] && echo "Setting LOCAL_IP=$LOCAL_IP"
    fi

    if [[ "$1" == "ximeraserver" ]]
    then    
        echo "Starting ximera $SERVER_NAME from $SERVER_IMAGE on port $SERVER_PORT"
        docker run --rm --name $SERVER_NAME -p 2000:$SERVER_PORT $SERVER_IMAGE
        exit
    fi

    echo "Restarting myself in docker (from image $DOCKER_IMAGE)"	
    [[ -n "$DEBUG" ]] && echo  \
    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --env DEBUG --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --env DEBUG --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
    exit 
fi

#
# The 'REAL' contents are ommitted in this version, but (presumably...) are present in the copy *inside* the container $DOCKER_IMAGE !!!!
#
echo "Sorry, this limited version of this xmlatex script should not be run *inside* a docker container. Find and run the full version, perhaps called xmlatex.full!"
exit 1
